# Generated by Django 4.2.28 on 2026-02-16 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('bankability_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sylistockapp.merchantprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sylistockapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_changed', models.IntegerField()),
                ('action', models.CharField(choices=[('IN', 'Restock'), ('OUT', 'Sale'), ('ADJ', 'Adjustment (Damage/Lost)')], max_length=3)),
                ('source', models.CharField(choices=[('ZEBRA', 'Zebra Laser Scanner'), ('PHONE', 'Mobile Camera Scan'), ('MANUAL', 'Manual Entry')], max_length=10)),
                ('device_id', models.CharField(help_text='Serial or UUID', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sylistockapp.merchantprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sylistockapp.product')),
            ],
            options={
                'verbose_name_plural': 'Inventory Logs',
            },
        ),
    ]
